# Generated by Django 4.1.7 on 2023-11-09 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категории товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('contacts', models.IntegerField(verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Поставщики',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('short_desc', models.TextField(verbose_name='Короткое описание')),
                ('long_desc', models.TextField(verbose_name='Длинное описание')),
                ('cost', models.FloatField(verbose_name='Цена')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_shop.category', verbose_name='Категория')),
                ('custom_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_shop.customers', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
                'ordering': ['time_update', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('sum_cost', models.FloatField(verbose_name='Сумма заказа')),
                ('in_trash', models.BooleanField(default=False, verbose_name='В корзине')),
                ('in_liked', models.BooleanField(default=False, verbose_name='В избранном')),
                ('is_applying', models.BooleanField(default=False, verbose_name='Оформляется')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('is_delivering', models.BooleanField(default=False, verbose_name='Доставляется')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Доставлен')),
                ('ID_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID клиента')),
                ('ID_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop.products', verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('ID_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_shop.customers', verbose_name='ID поставщика')),
                ('ID_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_shop.products', verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Поставки',
                'verbose_name_plural': 'Поставки',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CostChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('new_cost', models.FloatField(verbose_name='Измененная цена')),
                ('ID_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online_shop.products', verbose_name='ID товара')),
            ],
            options={
                'verbose_name': 'Изменение цен',
                'verbose_name_plural': 'Изменение цен',
                'ordering': ['date'],
            },
        ),
    ]
