# Generated by Django 4.1.7 on 2024-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default='', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='client_phone',
            field=models.TextField(default='', verbose_name='Номер телефона клиента'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.TextField(default='', verbose_name='Способ оплаты'),
        ),
    ]
